/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { LotusApi } from "@fern-api/lotus";

export interface Seller {
    name: string;
    address?: LotusApi.Address;
    phone?: string;
    email?: string;
}
