/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { LotusApi } from "@fern-api/lotus";
import * as core from "../../../../core";

export const Request: core.serialization.Schema<
    serializers.customers.create.Request.Raw,
    LotusApi.CustomerCreateRequest
> = core.serialization.lazyObject(async () => (await import("../../..")).CustomerCreateRequest);

export declare namespace Request {
    type Raw = serializers.CustomerCreateRequest.Raw;
}

export const Response: core.serialization.Schema<serializers.customers.create.Response.Raw, LotusApi.Customer> =
    core.serialization.lazyObject(async () => (await import("../../..")).Customer);

export declare namespace Response {
    type Raw = serializers.Customer.Raw;
}
