/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Client as CustomersClient } from "./api/resources/customers/client/Client";

export declare namespace LotusApiClient {
    interface Options {
        environment?: environments.LotusApiEnvironment | string;
        authorization?: core.Supplier<string>;
    }
}

export class LotusApiClient {
    constructor(private readonly options: LotusApiClient.Options) {}

    #customers: CustomersClient | undefined;

    public get customers(): CustomersClient {
        return (this.#customers ??= new CustomersClient(this.options));
    }
}
